### ISSUE TITLE
Migrate rubyforge documentation

### ISSUE THREAD

**Issue by carlesso** [dicom/ruby-dicom#57]
A lot of documentation link (also the gem one) refers to rubyforge.org, which has been shut down some months ago.

After some research I've been able to find a copy of all the pages at [archive.org](https://web.archive.org/web/20120802163335/http://dicom.rubyforge.org/).

Was wondering if you can put the documentation somewhere and update the link. Thanks for your work!

**Comment by dicom** [comment]
Thank you Enrico for the observation, and reminder. I actually started on an effort to move this to a github page some time ago, but somehow it stalled. I'll try my best to get it done as soon as possible. Stay tuned!

**Comment by carlesso** [comment]
Thanks a lot!

**Comment by dicom** [comment]
I have finally migrated the old homepages to my account's github domain:
http://dicom.github.io/ruby-dicom/

Sorry for taking so long!

**Comment by carlesso** [comment]
Yay! Thanks a lot.
