### ISSUE TITLE
Making a dicom from a png file

### ISSUE THREAD

**Issue by c0ze** [dicom/ruby-dicom#61]
I'm trying to make a dicom out of a png file (png file is the image of an ECG reading).
I'm not having much luck, is there somekind of a tutorial / example for creating new dicoms from existing images ?

here's my code :

```
    include DICOM
    include Magick

    dcm = DObject.new
    dcm.photometric_interpretation = "MONOCHROME2"
    dcm.bits_allocated = 8
    dcm.pixel_representation = 0
    dcm.patients_name = "My Name"
    dcm.patient_id = "some_id"
    dcm.study_id = "some_id"
    dcm.study_date =  Time.now.strftime "%Y%m%d"
    dcm.study_instance_uid ="some_id"
    dcm.series_instance_uid = "some_id"
    dcm.sop_class_uid = "some_id"
    dcm.media_storage_sop_class_uid = "some_id"
    dcm.image =  ImageList.new("db/samples/ecg/19.ecg.png").first

    dcm.write "sample.dcm"
```

The resulting file is a dicom file with all the information I provided, with a size of 2 MBs. (orginal png is like 84 KBs)

```
=> db/samples/ecg/19.ecg.png PNG 1651x1275 1651x1275+0+0 DirectClass 8-bit 83kb
```

is there any obvious mistakes I am doing ?

**Comment by dicom** [comment]
Hello Arda

I guess there is not a extremely easy way to do this currently. You will
have to manually create all the tags needed to represent a valid DICOM
object. I have sometimes thought about the possibility of creating a
convenience method for making a dicom file from image, but it has not been
implemented so far.

Basically you have two options:

1. Create everything from scratch. In addition to the tags you have created
above, which looks correct at a glance, you need all remaining tags for
your particular modality. A good suggestion would be to open a dicom file
for the same modality, and copy/create all tags present in your code.

2. Use a preexisting dicom file as a template. Load it in ruby-dicom,
change the tags which are necessary, insert your image data, then save.
This might be less work.

The fact that your dicom file is much larger than your original image file
is not a cause for alarm, it only means that in your dicom file, the pixel
data is uncompressed, whereas in your png file, it is compressed (thus
smaller).

Note that there are also convenience methods in ruby-dicom for creating
UIDs. I notice in your code that your uids are invalid strings.

Best regards,
Chris
