### ISSUE TITLE
get_image_pos() problem

### ISSUE THREAD

**Issue by omaromar80** [dicom/ruby-dicom#62]
what is the alternative method of get_image_pos() in new DICOM

**Comment by dicom** [comment]
I dont think you are supposed to use what get_image_pos once gave you (thats why it was removed in a rewrite a long time ago).

Why dont you tell me what you actually want to achieve, and I can try to give you a suggestion.

**Comment by omaromar80** [comment]
frames = dcm.value('0028,0008').strip.to_i
    rows = dcm.value('0028,0010').to_i
    cols = dcm.value('0028,0011').to_i
	
    assertEqual(1, frames)
    assertEqual(600, rows)
    assertEqual(900, cols)
    
    frame_size = rows * cols * 3
      
    buffer_size = frames * frame_size
      
    image_pos = dcm.get_image_pos()
      
    assertEqual(1, image_pos.size)
         
    image_data = dcm.get_image(image_pos[0])

I want to use a function to get the Image in image_data instead of get_image_pos() function

**Comment by omaromar80** [comment]
So I want to get the indexes that contain image data from the DICOM file

**Comment by dicom** [comment]
Some methods you can use:

```
# Image dimensions
dcm.num_rows
dcm.num_cols
dcm.num_frames

# Pixel data:
dcm.images # (rmagick)
dcm.narray # (NArray)
dcm.image_strings # (binary string blobs)
```

This should be enough to handle the image data. If not, please explain further what you want to do.

**Comment by omaromar80** [comment]
how can I get the indexes that contain image data from the DICOM file


*Eng.Omar Omar*
*TOMTEC Imaging System GMBH*

*Software Engineering and Systems Information*

*Analyzing, Designing, Programming and Developing Computer Systems.*
*Airlines and Airports Systems.*

*Email:   engomaromar80@gmail.com <engomaromar80@gmail.com>*

*Mob: +49 1 57 55 99 71 08*

*LinkedIn: https://de.linkedin.com/in/omar-omar-89b69124
<https://de.linkedin.com/in/omar-omar-89b69124>Address: HauptStrasse
18,84144 Geisenhausen, Germany*

**Comment by omaromar80** [comment]
just I want to get the images from DICOM file and to write them to the hard disk as png file format, how can I do this?

**Comment by dicom** [comment]
```
dcm.images.each_with_index do |image, i|
  image.normalize.write("image#{i}.png")
end
```

**Comment by omaromar80** [comment]
This not works I have the Exception
Exception (Magick::ImageMagickError): RegistryKeyLookupFailed `CoderModulesPath' @ error/module.c/GetMagickModulePath/666

**Comment by dicom** [comment]
I believe that looks like a problem with your RMagick/ImageMagick installation, and not related to ruby-dicom itself.

**Comment by omaromar80** [comment]
Just I want to get the first image from the dicom file

**Comment by dicom** [comment]
Ok, then you use the dcm.image method. Have a look at the documentation here:
http://www.rubydoc.info/gems/dicom/DICOM/ImageItem#image-instance_method

**Comment by omaromar80** [comment]
It was not working, the exported image is empty..

simply I have DICOM file with one image I have to write a simple function
to get this image from the file and to export it as PNG file, could you
please write the code here,

My code is :

dcm = DICOM::DObject.read("file_name.dcm")

pngFilePath = 'newImage.png'

image = dcm.image

but I can not find function to write the image to PNG file,

I used the code

image.normalize.write(pngFilePath )

but I got the exception

Exception : RegistryKeyLookupFailed `CoderModulesPath'

regards,

Omar

**Comment by dicom** [comment]
What you are doing is the correct way.@
The error you are getting seems to indicate that there is a problem with your imagemagick and/or RMagick installation. Try reinstalling imagemagick and rmagick. Also try to read and write a picture in rmagick without using ruby-dicom. If you get the same problem there, it demonstrates that it is not related to ruby-dicom.
