### ISSUE TITLE
dcm.value('0018,6018', :array => true) not working

### ISSUE THREAD

**Issue by omaromar80** [dicom/ruby-dicom#63]
why this method not working in the new version of DICOM

dcm.value('0018,6018', :array => true)

in the last version we write like this dcm.get_value('0018,6018', :array => true)
but in the new version dcm.value('0018,6018', :array => true)
not working

**Comment by dicom** [comment]
There is no options to the value method in ruby-dicom.

Please give an example of what dcm.value('0018,6018') returns, and what you would like it to return instead, if it does not give you what you want.

If you dont get what you want, I will consider enhancements if it is reasonable.
