### ISSUE TITLE
Deprecation warning for Ruby 2.4.0

### ISSUE THREAD

**Issue by codehugger** [dicom/ruby-dicom#65]
I got this warning when I upgraded to the latest official version of ruby.

/Users/codehugger/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/dicom-0.9.7/lib/dicom/stream.rb:64: warning: constant ::Fixnum is deprecated

**Comment by dicom** [comment]
Thank you for reporting this deprecation warning. I am aware that there has been a unification of Fixnum and Bignum into Integer in Ruby 2.4, but I havent actually tried 2.4 myself, so I havent seen this warning before. Obviously a patch need to be made for this.

**Comment by dicom** [comment]
This should be Fixed now.
