### ISSUE TITLE
Fail to see image data on OsiriX after annonymization

### ISSUE THREAD

**Issue by champierre** [dicom/ruby-dicom#69]
I use OsiriX(http://www.osirix-viewer.com/) to see DICOM files.
After I did simple annonymization described in tutorials to a DICOM file, image data does not appear on OsiriX.
I found that it is because "Transfer Syntax UID"(0002,0010) tags are removed, so I could fix the problem by skipping that process by overriding DICOM::Parent#delete_group method like the sample source below.
I am new to this medical industry, so not sure if this is a bug or not, but I want to send this feedback, so opened this issue.

```
require 'dicom'

module DICOM
  class Parent
    def delete_group(group_string)
      group_elements = group(group_string)
      group_elements.each do |element|
        next if element.tag == '0002,0010'
        delete(element.tag)
      end
    end
  end
end

dcm = DICOM::DObject.read('sensitive.dcm')
dcm.anonymize
dcm.write('clean.dcm')
```

**Comment by dicom** [comment]
I don't see this behaviour. It is true that in the instance you have just run the anonymize method, the 0002 group is removed, but this group, including the 0002.0010 tag is written to the file when you use the write method.

Best regards,
Christoffer
