### ISSUE TITLE
warning: constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by bjoernalbers** [dicom/ruby-dicom#72]
Hey Christoffer,

with the latest release (0.9.7) of `ruby-dicom` under Ruby 2.4 I get this warning:

> warning: constant ::Fixnum is deprecated

I found out that the issue is already fixed in master branch.
Could you please release an update (RubyGem)?

Thanks,
Björn

**Comment by dicom** [comment]
Hello Bjørn

Thanks for the heads up. I guess you are right, it is time for a new release. Ill try to make it happen ASAP.

Best regards,
Christoffer

**Comment by dicom** [comment]
Version 0.9.8 has been released with this fix.
