### ISSUE TITLE
Reference this gem into awesome-ruby

### ISSUE THREAD

**Issue by raulperezalejo** [dicom/ruby-dicom#77]
I found this gem extremely useful, so id like to suggest to add this gem to 
https://github.com/markets/awesome-ruby

thanks

**Comment by dicom** [comment]
Hello Raul

Thank you for this suggestion.

I agree that it would be nice to see the dicom gem on such a list.

I dont think it would be appropriate for myself as the creator to request this though. Why don't you create an issue on the awesome-ruby project, and ask for the addition of the dicom gem?!

Best regards,
Chris
