### ISSUE TITLE
Keen and interested to know any acttive development

### ISSUE THREAD

**Issue by arunjoshtech** [dicom/ruby-dicom#80]
Dear great team ,
This is really great honor for work.
But found no recent activities. I am requesting you all to do complete implementation like dcmtk.

**Comment by dicom** [comment]
Thank you for your feedback.

I am afraid "complete implementation like dcmtk" is both somewhat unspecific and potentially too big a scope for what we can practically achieve.

If there are specific features missing in ruby-dicom that makes you unable to use it, please feel free to create a request for that.

Best regards,
Chris
